### PR TITLE
Use HTTPS where possible

### PR DESCRIPTION
**Pull request by mathiasbynens**
I’ve also cleaned up the HTML a bit by removing unneeded attribute/value pairs.

### CODE REVIEW

**Comment by elsigh** [comment]
Will do a deploy today, thanks @mathiasbynens!

**Comment by mathiasbynens** [comment]
Please let me know when it’s deployed. Thanks!

**Comment by elsigh** [comment]
Done as of yesterday afternoon

**Comment by elsigh** [comment]
Actually, done as of right now - I needed to change the default version, derp. ;)

**Comment by mathiasbynens** [comment]
:+1:

**Pull request merged**
